### ISSUE TITLE
Selective download to reduce mirror size

### ISSUE THREAD

**Issue by altaurog** [AleXoundOS/haskell-stack-mirror-script#3]
Would it suffice in many use cases to download only what's included in a single snapshot and/or only the latest versions of packages?  I imagine that would significantly reduce the size of the mirror.

By the same token, including only specific packages (and their dependencies) or excluding specific packages might be useful, though perhaps less so for full offline functionality.

**Comment by AleXoundOS** [comment]
Well, the main idea is full offline functionality. It's sometimes difficult to predict which packages exactly you will need when you go offline, let's say, for 1 week or longer. Moreover the script downloads all hackage packages regardless if they present in stackage.

Latest versions of packages is definitely not what we want. Since there is no guarantee that each of them depend on the the latest version of another package.

Technically it's all possible of what you mention (and so it won't be a real mirror). However such kind of logical/db queries are very tricky to implement in bash, except simple exclude packages list. Currently there is no yaml AST parsing involved, but simple grep&sed filtering.

Ideally this script needs to be rewritten in Haskell, what will bring opportunity to add various additional functionality quite easily.

**Comment by AleXoundOS** [comment]
Btw, if you don't plan to share the partial mirror with others in local network and working locally on one machine is sufficient, most likely you do not need any mirrors.
Building the project once with stack is enough to continue to work offline with the packages required for the build.

**Comment by altaurog** [comment]
Okay, thanks for explaining.  Looking forward to a haskell version!

**Comment by AriFordsham** [comment]
Leaving out GHCs for other OSes and architectures should be safe, and would probably cut the download by about half.

**Comment by AleXoundOS** [comment]
> Leaving out GHCs for other OSes and architectures should be safe, and would probably cut the download by about half.

Maybe. Sorry, currently, I'm not aware if it's working at all since [the major changes](https://github.com/AleXoundOS/haskell-stack-mirror-script/issues/8) in stack. And personally suggest to use a combination of [haskell.nix](https://input-output-hk.github.io/haskell.nix/) + [mirror-hackage](https://github.com/AleXoundOS/mirror-hackage) instead of the haskell-stack-mirror-script.
